[workspace]
members = [
    "./ic-solidity-bindgen",
    "./ic-solidity-bindgen-macros"
]

[workspace.dependencies]
ic-web3-rs = { git = "https://github.com/horizonx-tech/ic-web3-rs.git", branch = "deps/ic-cdk-0.13.2" }
serde_json = "1.0.96"
