[workspace]
members = [
    "./ic-solidity-bindgen",
    "./ic-solidity-bindgen-macros"
]

[workspace.dependencies]
ic-web3-rs = { git = 'https://github.com/horizonx-tech/ic-web3-rs.git', branch = 'feature/fix-sign-method' }
serde_json = "1.0.96"
