[package]
name = "ic-solidity-bindgen-macros"
version = "0.1.0"
description = "A proc macro crate internal to ic-solidity-bindgen"
edition = "2021"

[badges]
maintenance = { status = "experimental" }

[lib]
proc-macro = true

[dependencies]
syn = "1.0.18"
quote = "1.0.3"
proc-macro2 = "1.0.10"
Inflector = "0.11.4"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
ic-web3-rs = "0.1.0"
